[Attu Metrics] Healthy Status View
zilliztech/attu pull request #168
Opened 2023-02-22 07:58 UTC by alwayslove2013

2023-02-22 09:30 UTC, nameczz requested changes

2023-02-22 09:30 UTC, nameczz commented on client/src/context/Prometheus.tsx
> +          } else openSnackBar(prometheusTrans('invalid'), 'error');
need {} after else

2023-02-22 09:30 UTC, nameczz commented on client/src/context/Prometheus.tsx
> +            // openSnackBar(prometheusTrans('ready'));
do we need it?

2023-02-22 09:30 UTC, nameczz commented on client/src/pages/systemHealthy/SystemHealthyView.tsx
> +              label: 'Search Latency',
i18n?

2023-02-22 09:30 UTC, nameczz commented on client/src/utils/Format.ts
> +  if (!withProtocol) formatAddress = 'http://' + formatAddress;
how about https:// ?

2023-02-22 09:30 UTC, nameczz commented on server/src/prometheus/prometheus.service.ts
> +        return false;
why not throw error?

2023-02-23 01:59 UTC, Tumao727 approved these changes

2023-02-23 07:50 UTC, alwayslove2013 commented on client/src/context/Prometheus.tsx
> +            // openSnackBar(prometheusTrans('ready'));
remove it

2023-02-23 07:51 UTC, alwayslove2013 commented on client/src/utils/Format.ts
> +  if (!withProtocol) formatAddress = 'http://' + formatAddress;
'https' also includes 'http'

2023-02-23 07:53 UTC, alwayslove2013 commented on server/src/prometheus/prometheus.service.ts
> +        return false;
the error will be thrown now.

2023-02-23 08:33 UTC, alwayslove2013 commented on client/src/pages/systemHealthy/SystemHealthyView.tsx
> +              label: 'Search Latency',
use i18n now

2023-02-24 02:53 UTC, shanghaikid approved these changes

2023-02-27 06:03 UTC, merged