[Issue 56] add IP param to metric type
zilliztech/attu pull request #64
Opened 2022-05-10 09:41 UTC by iynewz

support IP parameter when searching
![image](https://user-images.githubusercontent.com/81401074/167598997-ee4bab15-2fcb-4c4b-948e-3fba828473ba.png)
![image](https://user-images.githubusercontent.com/81401074/167599047-b52717dc-75b6-4333-8e3e-a3048ba424ea.png)
Successfully created the metric type:
![image](https://user-images.githubusercontent.com/81401074/167599250-205701f7-d80e-4a00-b37a-29276f0e64a6.png)

2022-05-10 09:46 UTC, iynewz commented
I clicked the search button and it shows **Invalid array length**
![image](https://user-images.githubusercontent.com/81401074/167600306-6a510646-b922-4ccb-a0f9-b1338194a2c5.png)
I am working on it currently.

2022-05-10 09:49 UTC, shanghaikid commented
> I clicked the search button and it shows **Invalid array length** and I am working on it currently. ![image](https://user-images.githubusercontent.com/81401074/167600306-6a510646-b922-4ccb-a0f9-b1338194a2c5.png) May I make a new pull request to fix the array length problem?

please fix in this pr.

2022-05-10 10:04 UTC, nameczz requested changes

2022-05-10 10:04 UTC, nameczz commented on client/src/plugins/search/VectorSearch.tsx
> +            metricType={selectedMetricType || metricType!}
same here

2022-05-10 11:33 UTC, iynewz commented on client/src/components/grid/LoadingTable.tsx
> +  //TODO(wenyi): There is a bug here, count is always -1, so returns Error: Invalid array length
I think it is because when screen height is too small, the `offsetHeight` of container is smaller and  `count ` may be negative.

2022-05-10 13:20 UTC, iynewz commented on client/src/components/grid/LoadingTable.tsx
> +  //TODO(wenyi): There is a bug here, count is always -1, so returns Error: Invalid array length
I fixed this problem by limiting the value of height, making it not smaller than the height of container header. Please take a look again

2022-05-11 03:10 UTC, Tumao727 approved these changes

2022-05-11 03:11 UTC, nameczz approved these changes

2022-05-11 03:12 UTC, merged

2022-05-11 03:40 UTC, iynewz commented
colse #56